/** Fictional coverage facts. Windows include both end days. */
export const SCENES = [
 {eyebrow:'01 / The question', title:'Your database<br><em>says 26.</em>', caption:'How did it get here?', aside:'A short scroll story about rebuilding subscription tracking for a SAAS product. A seat is one staff member the customer can manage.', noteTitle:'A current value needs an explanation', note:'On day 25 Aster Studio can manage 26 staff. That number is the result of a purchase, a temporary grant and an applied correction. The app stores the current answer in a materialised projection; the signed coverage ledger keeps the facts that explain it.', facts:[{label:'Current answer',value:'26 seats on day 25'},{label:'Underlying facts',value:'+20, +10, −4'}]},
 {eyebrow:'02 / Before · The old table', title:'Before,<br><em>a&thinsp;number.</em>', caption:'The old table kept one record per subscription and updated it in place. The number was current. The reason was gone.', noteTitle:'What the single record could not tell you', note:'The stored status often disagreed with the record\'s own dates. Explaining a seat count meant digging through orders and edit logs. Staff access was switched on and off from that one record, so a wrong record silently granted or removed access. Nothing recorded which change produced the current number.', facts:[{label:'Records per subscription',value:'One'},{label:'On every change',value:'Update in place'},{label:'Why 26?',value:'No record'}]},
 {eyebrow:'03 / After · The ledger', title:'After,<br><em>a&thinsp;ledger.</em>', caption:'Same customer, new table. Every change is a dated record that is never edited. Purchase means the paid plan, temporary means bonus days, correction means a fix by support.', noteTitle:'Keep each contribution and its window', note:'The purchase contributes 20 seats on days 1 through 45. The temporary grant contributes 10 on days 15 through 30. An applied correction contributes minus 4 on days 20 through 45. Each record keeps its origin and window. Corrections append signed records rather than rewriting earlier facts.', facts:[{label:'Purchase',value:'+20 · days 1–45'},{label:'Temporary grant',value:'+10 · days 15–30'},{label:'Applied correction',value:'−4 · days 20–45'}]},
 {eyebrow:'04 / After · Time moves', title:'Same facts.<br><em>Different day.</em>', caption:'The temporary grant ends on day 30. Its record stays. On day 31 only the purchase and the correction cover the date: 20 − 4 = 16.', noteTitle:'Coverage changes even when the records do not', note:'For any day, add the signed counts of the records whose window covers it. The complete model folds trial and paid coverage separately, with paid coverage taking precedence. Some subscription types use presence pulses instead of seat counts. The animation follows one paid seat example so the calculation stays visible.', facts:[{label:'Day 25',value:'20 + 10 − 4 = 26'},{label:'Day 31',value:'20 − 4 = 16'},{label:'Records kept',value:'All three'}]},
 {eyebrow:'05 / After · The stored answer', title:'Calculate it.<br><em>Keep the answer ready.</em>', caption:'Every request checks the seat limit. Summing the ledger each time is too slow, so the answer is stored once and refreshed when a record is written or the date moves.', noteTitle:'The projection is a stored view of the ledger', note:'The materialised projection stores current coverage per account and subscription type. Login checks, the billing page and staff access flags all read it. Writers refresh affected projections inside their transaction. Date transitions use a reactive daily refresh. The ledger stays authoritative and can rebuild the projection at any time.', facts:[{label:'Source',value:'Signed coverage ledger'},{label:'Stored current view',value:'Paid · active · 16 seats'},{label:'Refresh',value:'Writes and date transitions'}]},
 {eyebrow:'06 / After · Keep both', title:'Keep the facts.<br><em>Store the answer.</em>', caption:'Support can explain any number. The app reads one record. Change the day below to try it.', noteTitle:'An answer you can explain and rebuild', note:'The ledger keeps each signed contribution, its coverage window and where it came from. The materialised projection makes current reads cheap. Keeping both lets the system explain its current answer and rebuild derived state. Try another day below, or open the side stories on approvals and migration.', facts:[{label:'History',value:'Three dated facts'},{label:'Current view, day 31',value:'16 seats'},{label:'Explore',value:'Change the day below'}]}
];
export function getStoryState(scene, phase) {
 scene=Math.max(0,Math.min(5,Number.isFinite(scene)?Math.floor(scene):0));
 phase=Math.max(0,Math.min(1,Number.isFinite(phase)?phase:0));
 const day=scene<3?25:scene===3?25+Math.min(6,Math.floor(phase*7)):31;
 const temporary=day>=15&&day<=30;
 return {scene,phase,day,total:20+(temporary?10:0)-4,temporary,correction:true,applied:true,numberLabel:scene===0?'Current seat limit':scene===1?'Old table · one record':scene>=4?'New table · materialized view':'New ledger · calculated'};
}
