/** Fictional coverage facts. Windows include both end days. */
export const SCENES = [
 {eyebrow:'01 / Current state', title:'Your database<br><em>says 26.</em>', caption:'How did it get here?', noteTitle:'A current value needs an explanation', note:'Aster Studio is a fictional account. On day 25 its paid seat limit is 26. That value is the result of a purchase, a temporary grant and an applied correction. The materialised projection stores the current answer; the signed coverage ledger retains the facts that explain it. The example illustrates the architecture, not production customer data.', facts:[{label:'Current answer',value:'26 seats on day 25'},{label:'Underlying facts',value:'+20, +10, −4'}]},
 {eyebrow:'02 / History', title:'Every change<br><em>left a fact.</em>', caption:'A purchase. A temporary grant. An applied correction.', noteTitle:'Keep each contribution and its window', note:'The purchase contributes 20 seats on days 1 through 45. The temporary grant contributes 10 on days 15 through 30. An applied correction contributes minus 4 on days 20 through 45. Each row retains its origin and window. Corrections append signed rows rather than rewriting earlier facts. These are dated coverage facts, not a claim that every historical application state can be reconstructed from an event stream.', facts:[{label:'Purchase',value:'+20 · days 1–45'},{label:'Temporary grant',value:'+10 · days 15–30'},{label:'Applied correction',value:'−4 · days 20–45'}]},
 {eyebrow:'03 / Time moves', title:'Same facts.<br><em>Different day.</em>', caption:'The temporary grant ends. Its record stays.', noteTitle:'Coverage changes even when the rows do not', note:'Scroll from day 25 to day 31. The temporary grant covers day 30, but not day 31. The calculated seat total falls from 26 to 16. All three records remain in the ledger. This animation shows the date-derived answer. In the application, stored projections cross date boundaries through a reactive daily refresh; authorization does not guarantee a new fold on every access.', facts:[{label:'Day 25',value:'20 + 10 − 4 = 26'},{label:'Day 31',value:'20 − 4 = 16'},{label:'Records retained',value:'All three'}]},
 {eyebrow:'04 / Derive the answer', title:'What applies<br><em>today?</em>', caption:'Follow the date. Add the facts that cover it.', noteTitle:'Fold the coverage windows', note:'For day 31, the purchase and correction contribute, while the expired temporary grant does not. Their signed counts sum to 16. The complete model folds trial and paid coverage separately, with paid coverage taking precedence under its rules. Some subscription types use presence pulses instead of seat counts. The animation follows one paid seat example so the calculation stays visible.', facts:[{label:'Chosen day',value:'31'},{label:'Contributing rows',value:'+20 and −4'},{label:'Derived limit',value:'16 seats'}]},
 {eyebrow:'05 / Materialized view', title:'Calculate it.<br><em>Keep the answer ready.</em>', caption:'Store the current view. Let the app read it.', noteTitle:'The projection is a stored view of the ledger', note:'The materialised projection stores current coverage per account and subscription type. The entitlement facade reads it. Display summaries combine projection data with commercial history, and relevant state changes refresh staff access flags. Writers refresh affected projections inside their transaction. Date transitions use a reactive daily refresh. The ledger remains authoritative and can rebuild the derived answer.', facts:[{label:'Source',value:'Signed coverage ledger'},{label:'Stored current view',value:'Paid · active · 16 seats'},{label:'Refresh',value:'Writes and date transitions'}]},
 {eyebrow:'06 / History → current state', title:'Preserve the history.<br><em>Derive the present.</em>', caption:'The current answer stays connected to the facts behind it.', noteTitle:'An answer you can explain and rebuild', note:'The ledger retains each signed contribution, its coverage window and its provenance. The materialised projection makes current reads practical. Keeping both lets the system explain its current answer and rebuild derived state. Try another day below, or explore how approvals and migration fit around this model.', facts:[{label:'History',value:'Three dated facts'},{label:'Current view, day 31',value:'16 seats'},{label:'Explore',value:'Change the day below'}]}
];
export function getStoryState(scene, phase) {
 scene=Math.max(0,Math.min(5,Number.isFinite(scene)?Math.floor(scene):0));
 phase=Math.max(0,Math.min(1,Number.isFinite(phase)?phase:0));
 const day=scene<2?25:scene===2?25+Math.min(6,Math.floor(phase*7)):31;
 const temporary=day>=15&&day<=30;
 return {scene,phase,day,total:20+(temporary?10:0)-4,temporary,correction:true,applied:true,numberLabel:scene===0?'Current seat limit':scene>=4?'Materialized view':'Calculated seats'};
}
